tailwind.config.ts

Revert "tailwindcssに型付け"

---

src/app/colors/contrasts/_components/check-contrast/check-contrast.stories.tsx
src/app/colors/contrasts/_components/check-contrast/check-contrast.tsx
src/app/colors/contrasts/_components/check-contrast/index.ts
src/app/colors/contrasts/_components/description/description.stories.tsx
src/app/colors/contrasts/_components/description/description.tsx
src/app/colors/contrasts/_components/description/index.ts
src/app/colors/contrasts/_components/result-table/index.ts
src/app/colors/contrasts/_components/result-table/result-table.stories.tsx
src/app/colors/contrasts/_components/result-table/result-table.tsx
src/app/colors/contrasts/page.tsx

コントラスト比チェッカーのリファクタ

---

renovate.json

renovateを週末に実行させる

---

src/app/quizzes/_components/collection/collection.tsx
src/app/quizzes/fish-kanji/list/loading.tsx
src/app/quizzes/fish-kanji/loading.tsx
tailwind.config.ts

close https://github.com/k35o/k8o/issues/159

クイズの一覧を中央に寄せる

---

.github/workflows/chromatic.yml

close https://github.com/k35o/k8o/issues/160

renovateではchromaticの実行を待機させる

---

package.json
pnpm-lock.yaml
src/app/@modal/_components/modal/modal.tsx
src/app/blog/_components/external-blog/external-blog.tsx
src/app/characters/check-syntax/_components/result/result.tsx
src/app/characters/check-syntax/_components/syntax-fixer/syntax-fixer.tsx
src/app/characters/check-syntax/_components/verified-syntax/verified-syntax.tsx
src/app/colors/converter/_components/color-converter/color-converter.stories.tsx
src/app/colors/converter/_components/color-converter/color-converter.tsx
src/app/number/converter/_components/base-converter/base-converter.stories.tsx
src/app/number/converter/_components/base-converter/base-converter.tsx
src/app/page.tsx
src/app/sql-statement/_components/create-columns/create-columns-by-form.tsx
src/app/sql-statement/_components/create-columns/create-columns-by-table.tsx
src/app/sql-statement/_components/create-columns/create-columns.tsx
src/app/sql-statement/_components/create-restrictions/create-restrictions.tsx
src/components/accordion/accordion-button.tsx
src/components/alert-icon/alert-icon.tsx
src/components/button/button.stories.tsx
src/components/form/autocomplete/autocomplete.tsx
src/components/form/checkbox/checkbox.tsx
src/components/form/select/select.tsx
src/components/icon-button/icon-button.stories.tsx
src/components/icon-link/icon-link.stories.tsx
src/components/icons/icons.stories.tsx
src/components/icons/index.ts
src/components/link-button/link-button.stories.tsx

Iconのライブラリをlucideに変更

---

.storybook/preview.tsx
src/hooks/interval/index.test.ts
src/hooks/interval/index.ts
src/utils/date/format.ts

それが必要だったあるものは作らないかもしれない
このアプリは色々なものを作る時に参照したいので、使っていないものも追加しちゃう

あるものを作りたくて作ったutilsを追加

---

.github/workflows/chromatic.yml

stopしてるけどsnapshot動いてるっぽいのでコマンドから止める

renovateブランチは実行をスキップする

---

renovate.json

Revert "pnpmとnodeを含めないように"

---

src/app/_components/app-card/app-card.stories.tsx
src/app/_components/app-card/app-card.tsx
src/app/_styles/globals.css
src/app/designs/_components/rounded-icon/index.ts
src/app/designs/_components/rounded-icon/rounded-icon.stories.tsx
src/app/designs/_components/rounded-icon/rounded-icon.tsx
src/app/designs/layout.tsx
src/app/designs/opengraph-image.tsx
src/app/designs/page.tsx
src/app/designs/rounded/_components/control-panel/control-panel.stories.tsx
src/app/designs/rounded/_components/control-panel/control-panel.tsx
src/app/designs/rounded/_components/control-panel/index.ts
src/app/designs/rounded/_components/control-panel/use-control-panel.ts
src/app/designs/rounded/layout.tsx
src/app/designs/rounded/opengraph-image.tsx
src/app/designs/rounded/page.tsx
src/app/designs/rounded/twitter-image.tsx
src/app/designs/twitter-image.tsx
src/app/number/layout.tsx
src/app/page.tsx
src/components/icon-button/icon-button.stories.tsx
src/components/icon-button/icon-button.tsx
src/components/icon-link/icon-link.stories.tsx
src/design/color.stories.tsx
src/utils/number/between.ts
tailwind.config.ts

closed https://github.com/k35o/k8o/issues/226

角丸調整ページの作成

---

src/app/designs/rounded/_components/control-panel/use-control-panel.ts

closed https://github.com/k35o/k8o/issues/267

スクロールをしたくない

---

src/app/_styles/globals.css
src/components/button/button.stories.tsx
src/components/button/button.tsx
src/components/dropdown-menu/dropdown-menu.tsx
src/components/list-box/list-box.tsx
src/components/popover/popover.tsx
src/design/color.stories.tsx
src/mdx-components.tsx
tailwind.config.ts

fixed https://github.com/k35o/k8o/issues/295

ドロップダウン用のボタンとしてグレースケールのボタンを作る

---

src/components/form/number-field/number-field.tsx

NumberFieldがiosでは表示がバグる問題の解決

---

src/app/base-converter/_components/base-converter/base-converter.tsx
src/app/color-converter/_components/color-converter/color-converter.tsx
src/app/quizzes/_components/answer/answer.tsx
src/app/sql-table-builder/_components/create-columns/create-columns-by-form.tsx
src/app/sql-table-builder/_components/create-columns/create-columns-by-table.tsx
src/app/sql-table-builder/_components/create-restriction/create-restriction.tsx
src/app/sql-table-builder/_components/create-table/create-table.tsx
src/components/form/checkbox/checkbox.stories.tsx
src/components/form/checkbox/checkbox.tsx
src/components/form/form-control/form-control.stories.tsx
src/components/form/radio/radio.stories.tsx
src/components/form/radio/radio.tsx
src/components/form/select/select.stories.tsx
src/components/form/select/select.tsx
src/components/form/text-field/text-field.stories.tsx
src/components/form/text-field/text-field.tsx

resolved: https://github.com/k35o/k8o/issues/455

formのchangeをeventを元に行うように

---

.github/workflows/neon.yml

resolved https://github.com/k35o/k8o/issues/490

PRごとにNeonのデータベースを作成する

---

.github/workflows/deploy-preview.yml
package.json

resolved https://github.com/k35o/k8o/issues/498
resolved https://github.com/k35o/k8o/issues/491

Vercel preview

---

next.config.ts

next.config.jsのTypeScript対応

---

.env.example
.github/workflows/deploy-preview.yml
README.md
docker-compose.yml
drizzle.config.ts
migrations/0009_low_captain_stacy.sql
migrations/0010_famous_bloodstorm.sql
migrations/meta/0009_snapshot.json
migrations/meta/0010_snapshot.json
migrations/meta/_journal.json
package.json
pnpm-lock.yaml
src/drizzle/README.md
src/drizzle/db.ts

resolved https://github.com/k35o/k8o/issues/488
resolved https://github.com/k35o/k8o/issues/487
resolved https://github.com/k35o/k8o/issues/436
resolved https://github.com/k35o/k8o/issues/434
resolved https://github.com/k35o/k8o/issues/433

Local開発環境の整備

---

.github/workflows/deploy-preview.yml

https://github.com/k35o/k8o/issues/512

neonのブランチ作成をmigrationがある時だけにする

---

src/app/_components/comming-soon/comming-soon.stories.tsx
src/app/_components/comming-soon/comming-soon.tsx
src/app/_components/comming-soon/index.ts
src/app/base-converter/layout.tsx
src/app/color-converter/layout.tsx
src/app/contrast-checker/layout.tsx
src/app/design-system/_components/color/color-info/color-info.tsx
src/app/design-system/layout.tsx
src/app/design-system/opengraph-image.tsx
src/app/design-system/page.tsx
src/app/design-system/twitter-image.tsx
src/app/page.tsx
src/app/radius-maker/layout.tsx
src/components/icons/icons.stories.tsx
src/components/tabs/tabs.tsx

resolved: https://github.com/k35o/k8o/issues/350

Arteodyssey デザインシステムページの作成

---

src/app/design-system/_components/color/color.stories.tsx
src/app/design-system/_components/color/color.tsx
src/app/design-system/_components/radius/radius.stories.tsx
src/app/design-system/_components/radius/radius.tsx
src/app/design-system/_components/typography/index.ts
src/app/design-system/_components/typography/typography.stories.tsx
src/app/design-system/_components/typography/typography.tsx
src/app/design-system/page.tsx

closed: https://github.com/k35o/k8o/issues/472

Typographyの整理

---

.github/workflows/deploy-preview.yml

closed https://github.com/k35o/k8o/issues/577

labelを元に判定するように

---

src/app/design-system/_components/spacing/index.ts
src/app/design-system/_components/spacing/spacing.stories.tsx
src/app/design-system/_components/spacing/spacing.tsx
src/app/design-system/page.tsx

resolved: https://github.com/k35o/k8o/issues/473

spacing一覧の作成

---

migrations/0014_fair_speed.sql
migrations/meta/0014_snapshot.json
migrations/meta/_journal.json
src/app/blog/intl-duration-format/layout.tsx
src/app/blog/intl-duration-format/opengraph-image.tsx
src/app/blog/intl-duration-format/page.mdx
src/app/blog/intl-duration-format/twitter-image.tsx

resolved: https://github.com/k35o/k8o/issues/594

Intl.DurationFormatについてのブログを作成

---

src/app/_components/toggle-theme/toggle-theme.tsx
src/providers/app.tsx

MotionConfigでreducermotionの設定を行う

---

next.config.ts
package.json
src/app/_styles/globals.css
src/app/blog/_components/blog-card/blog-card.tsx
src/app/blog/_components/blog-layout/blog-layout.tsx
src/app/blog/_components/blog-layout/tags/tags.tsx
src/libs/react.ts
src/mocks/libs/react.mock.ts

ブログ間のViewTransitionを変更する

---

src/app/blog/_components/blog-card/blog-card.tsx
src/app/blog/_components/blog-layout/blog-layout.tsx

全体をトランジションすると核つくので内側のテキスト類だけにする

---

src/database/schema/index.ts
src/database/schema/subscribers.ts
src/emails/verify-email.tsx
src/services/subscription/index.ts
src/services/subscription/subscribe.ts
src/services/subscription/verify.ts
src/services/type.ts
src/utils/date/compare.ts

購読者を登録するテーブルの作成

---

migrations/0026_tense_hellfire_club.sql
migrations/meta/0026_snapshot.json
migrations/meta/_journal.json

migrationファイルの作成

---

src/mocks/db.mock.ts
vitest.workspace.ts

services testの準備

---

src/app/api/subscriptions/verify/route.ts
src/app/subscriptions/page.tsx
src/components/icons/icons.stories.tsx
src/components/icons/lucide.tsx
src/emails/verify-email.tsx
src/services/subscriptions/__test__/verify.test.ts
src/services/subscriptions/verify.ts

[WIP]サイトの購読をできるように

---

src/app/_components/global-layout/navigation-menu/navigation-menu.tsx
src/app/_components/toggle-theme/toggle-theme.tsx
src/app/blog/_components/external-blog/external-blog.tsx
src/app/page.tsx
src/components/dialog/dialog.tsx
src/components/dropdown-menu/dropdown-menu.tsx
src/components/icon-button/icon-button.tsx
src/components/icon-link/icon-link.tsx
src/components/list-box/list-box.tsx

Iconだけの時のlabelをsr-onlyに統一

---

.env.example

RESEND_API_KEYを追加

---

migrations/0027_bored_daimon_hellstrom.sql
migrations/0028_charming_texas_twister.sql
migrations/0029_stiff_talon.sql
migrations/meta/0027_snapshot.json
migrations/meta/0028_snapshot.json
migrations/meta/0029_snapshot.json
migrations/meta/_journal.json
src/app/blog/_services/index.ts
src/database/schema/blogs.ts

投稿予定のブログを設定可能に

---

src/app/blog/(articles)/react19-usereducer-ts-type-inference/layout.tsx
src/app/blog/(articles)/react19-usereducer-ts-type-inference/page.mdx

TSKaigiのブログのページだけ先に作成する(metadataもなし)

---

.storybook/preview.tsx
lefthook.yml
src/app/_components/global-layout/global-layout.tsx
src/components/drawer/drawer.tsx
src/components/modal/modal.tsx

resolved: https://github.com/k35o/k8o/issues/738

Modalのサイズ調整

---

.env.example
package.json
pnpm-lock.yaml
src/app/layout.tsx

resolved: https://github.com/k35o/k8o/issues/735

AnalyticsをVercelからGoogleに移行する

---

src/app/blog/(articles)/async-clipboard/layout.tsx
src/app/blog/(articles)/atomics-pause/layout.tsx
src/app/blog/(articles)/color-certification-uc/layout.tsx
src/app/blog/(articles)/color-contrast/layout.tsx
src/app/blog/(articles)/color-perception/layout.tsx
src/app/blog/(articles)/contenteditable-plaintextonly/layout.tsx
src/app/blog/(articles)/float16array/layout.tsx
src/app/blog/(articles)/intl-duration-format/layout.tsx
src/app/blog/(articles)/iterator-methods/layout.tsx
src/app/blog/(articles)/popover/layout.tsx
src/app/blog/(articles)/promise-try/layout.tsx
src/app/blog/(articles)/screen-wake-lock/layout.tsx
src/app/blog/(articles)/single-color-gradients/layout.tsx
src/app/blog/(articles)/tanstack-router-introduction/layout.tsx
src/app/blog/_components/external-blog/external-blog.tsx
src/app/blog/feed/route.ts
src/app/llms.txt/route.ts
src/components/icons/icons.stories.tsx
src/components/icons/lucide.tsx
src/utils/mdx/frontmatter.ts

llms.txtの追加

---

.storybook/public/mockServiceWorker.js

mockServiceWorker.jsの更新

---

src/mdx-components.tsx

blogにblockquoteを追加

---

src/app/blog/(articles)/react19-usereducer-ts-type-inference/layout.tsx

VERCEL_ENVを見てPreviewは表示させるように

---

migrations/0030_lazy_mach_iv.sql
migrations/0031_nappy_cobalt_man.sql
migrations/meta/0030_snapshot.json
migrations/meta/0031_snapshot.json
migrations/meta/_journal.json
src/app/tags/[id]/page.tsx
src/app/tags/_components/tag-card/index.ts
src/app/tags/_components/tag-card/tag-card.stories.tsx
src/app/tags/_components/tag-card/tag-card.tsx
src/app/tags/_components/tag-content/index.ts
src/app/tags/_components/tag-content/tag-content.stories.tsx
src/app/tags/_components/tag-content/tag-content.tsx
src/app/tags/layout.tsx
src/app/tags/page.tsx
src/components/card/interactive-card.tsx
src/database/schema/index.ts
src/database/schema/service-tag.ts
src/database/schema/service-type.ts
src/database/schema/services.ts
src/database/schema/tags.ts
src/services/tags/index.test.ts
src/services/tags/index.ts

タグの一覧機能を作る

---

src/app/_components/global-layout/global-layout.tsx
src/app/_components/global-layout/navigation-menu/navigation-menu.tsx
src/app/_components/global-layout/tags-link/index.ts
src/app/_components/global-layout/tags-link/tags-link.stories.tsx
src/app/_components/global-layout/tags-link/tags-link.tsx
src/app/blog/_components/blog-layout/tags/tags.tsx
src/app/tags/_components/tag-card/tag-card.stories.tsx
src/app/tags/_components/tag-card/tag-card.tsx
src/app/tags/_components/tag-content/tag-content.tsx
src/app/tags/page.tsx
src/components/text-tag/text-tag.stories.tsx
src/components/text-tag/text-tag.tsx

タグページの強化とリンクをつける

---

package.json
pnpm-workspace.yaml

pnpmの設定をpackage.jsonから剥がす

---

src/app/tags/_components/tag-card/tag-card.tsx
src/components/card/interactive-card.tsx

Tag card にアニメーションをつける

---

src/database/README.md

schema画像の更新

---

src/app/_components/global-layout/global-layout.tsx
src/app/_components/global-layout/navigation-menu/navigation-menu.tsx
src/app/tags/_components/tag-content/tag-content.stories.tsx
src/app/tags/_components/tag-content/tag-content.tsx
src/app/tags/page.tsx
src/database/schema/tags.ts
src/services/tags/index.test.ts
src/services/tags/index.ts

タグ一覧にtalksも表示する

---

.github/workflows/ci.yml
.ls-lint.yml
lefthook.yml
package.json
pnpm-lock.yaml

ls-lintのお試し導入

---

.github/workflows/erd.yml

refactor comments

---

src/database/README.md

resolved: https://github.com/k35o/k8o/issues/784

docs: ER図のURLと自動更新の説明を追加

---

migrations/0037_cynical_smiling_tiger.sql
migrations/meta/0037_snapshot.json
migrations/meta/_journal.json
src/app/blog/(articles)/requestclose/_components/example1.tsx
src/app/blog/(articles)/requestclose/layout.tsx
src/app/blog/(articles)/requestclose/opengraph-image.tsx
src/app/blog/(articles)/requestclose/page.mdx
src/app/blog/(articles)/requestclose/twitter-image.tsx

requestcloseの記事作成

---

.storybook/main.ts
.storybook/preview.tsx
.storybook/public/mockServiceWorker.js
package.json
pnpm-lock.yaml

storybook-addon-mock-dateの導入

---

src/app/page.tsx

k35o53kからk8omeに

---

.gitignore
CLAUDE.md

Add claude md documentation

---

migrations/0039_massive_ozymandias.sql
migrations/meta/0039_snapshot.json
migrations/meta/_journal.json
src/app/blog/(articles)/print-color-adjust/_components/example1.tsx
src/app/blog/(articles)/print-color-adjust/layout.tsx
src/app/blog/(articles)/print-color-adjust/opengraph-image.tsx
src/app/blog/(articles)/print-color-adjust/page.mdx
src/app/blog/(articles)/print-color-adjust/twitter-image.tsx

resolved: https://github.com/k35o/k8o/issues/811

print-color-adjustを記述

---

src/app/blog/(articles)/print-color-adjust/page.mdx

cssのコメントアウト修正

---

src/app/qr-generator/_components/qr-generator/qr-generator.tsx

shadowを消してbgにする

---

src/app/_components/global-layout/global-layout.tsx
src/app/_components/global-layout/header/header.tsx
src/app/_components/global-layout/header/index.ts
src/hooks/scroll-direction/index.test.ts
src/hooks/scroll-direction/index.ts

Sticky headerの見直し

---

src/app/contrast-checker/_components/description/description.tsx
src/app/contrast-checker/_components/result-table/result-table.tsx
src/app/design-system/_components/radius/radius.tsx
src/app/design-system/_components/typography/typography.tsx
src/app/design-system/page.tsx
src/app/talks/_components/talk-card/talk-card.tsx
src/components/baseline-status/baseline-status.tsx
src/components/breadcrumb/breadcrumb.tsx
src/components/heading/heading.tsx
src/components/link-card/link-card.tsx
src/components/tabs/tabs.tsx

小さな画面での見た目を改善する

---

migrations/0041_sleepy_catseye.sql
migrations/meta/0041_snapshot.json
migrations/meta/_journal.json
src/app/blog/(articles)/suspense-list/examples/example1/data.ts
src/app/blog/(articles)/suspense-list/examples/example1/example1.tsx
src/app/blog/(articles)/suspense-list/examples/example1/index.ts
src/app/blog/(articles)/suspense-list/layout.tsx
src/app/blog/(articles)/suspense-list/opengraph-image.tsx
src/app/blog/(articles)/suspense-list/page.mdx
src/components/form/checkbox/checkbox.tsx

SuspenseListの記事作成

---

src/app/blog/(articles)/suspense-list/examples/example1/example1.tsx

promiseを上から流す

---

src/app/qr-generator/opengraph-image.tsx
src/app/tags/_components/tag-card/tag-card.tsx
src/components/card/interactive-card.tsx

アニメーションを抑える

---

renovate.json5
src/app/blog/(articles)/async-clipboard/opengraph-image.tsx
src/app/blog/(articles)/atomics-pause/opengraph-image.tsx
src/app/blog/(articles)/color-certification-uc/opengraph-image.tsx
src/app/blog/(articles)/color-contrast/opengraph-image.tsx
src/app/blog/(articles)/color-perception/opengraph-image.tsx
src/app/blog/(articles)/contenteditable-plaintextonly/opengraph-image.tsx
src/app/blog/(articles)/float16array/opengraph-image.tsx
src/app/blog/(articles)/for-the-first-time-in-forever/opengraph-image.tsx
src/app/blog/(articles)/intl-duration-format/opengraph-image.tsx
src/app/blog/(articles)/iterator-methods/opengraph-image.tsx
src/app/blog/(articles)/json-modules/opengraph-image.tsx
src/app/blog/(articles)/popover/opengraph-image.tsx
src/app/blog/(articles)/print-color-adjust/opengraph-image.tsx
src/app/blog/(articles)/promise-try/opengraph-image.tsx
src/app/blog/(articles)/react19-usereducer-ts-type-inference/opengraph-image.tsx
src/app/blog/(articles)/regexp-escape/opengraph-image.tsx
src/app/blog/(articles)/requestclose/opengraph-image.tsx
src/app/blog/(articles)/screen-wake-lock/opengraph-image.tsx
src/app/blog/(articles)/single-color-gradients/opengraph-image.tsx
src/app/blog/(articles)/suspense-list/opengraph-image.tsx
src/app/blog/(articles)/tanstack-router-introduction/opengraph-image.tsx
src/app/qr-generator/opengraph-image.tsx

jsパーサーデフォルトで読み込む

---

renovate.json5

packageRulesにstorybook関連のパッケージを除外する条件を追加

---

migrations/0043_lean_nitro.sql
migrations/meta/0043_snapshot.json
migrations/meta/_journal.json
src/app/blog/(articles)/highlight/_components/example1.tsx
src/app/blog/(articles)/highlight/_components/example2.tsx
src/app/blog/(articles)/highlight/_components/example3.tsx
src/app/blog/(articles)/highlight/layout.tsx
src/app/blog/(articles)/highlight/opengraph-image.tsx
src/app/blog/(articles)/highlight/page.mdx
src/app/blog/(articles)/spelling-grammar-error/_components/example1.tsx
src/app/blog/(articles)/spelling-grammar-error/layout.tsx
src/app/blog/(articles)/spelling-grammar-error/opengraph-image.tsx
src/app/blog/(articles)/spelling-grammar-error/page.mdx
src/services/blogs/blogs.ts

CSS Custom Highlight APIのと::spelling-errorと::grammar-errorの記事作成

---

.gitignore
package.json
pnpm-lock.yaml
turbo.json

turborepoの導入

---

core/migrations/0044_organic_gwen_stacy.sql
core/migrations/meta/0044_snapshot.json
core/migrations/meta/_journal.json
core/src/app/blog/(articles)/sb-mock/layout.tsx
core/src/app/blog/(articles)/sb-mock/opengraph-image.tsx
core/src/app/blog/(articles)/sb-mock/page.mdx

resolved: https://github.com/k35o/k8o/issues/979

sb.mockの記事を書く

---

.github/workflows/claude-code-review.yml

Added repository and pull request number to the prompt for better context in reviews.

Enhance prompt with repository and PR number
